name: Build Flet APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build APK
        uses: flet-dev/flet-build-action@v1
        with:
          target: apk
          project-dir: .
          main-path: main.py
          runner-python-version: "3.11"
